version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internal-network
    ports:
      - 9080:9080
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
    entrypoint: /bin/wait-for-it.sh -t 0 minio:9000 -- /entrypoint.sh
    depends_on:
      - minio
  etcd:
    image: bitnami/etcd
    networks:
      - internal-network
    expose:
      - 2379
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
  minio:
    build: ./minio
    volumes:
      - ./storage:/storage
    networks:
      - internal-network
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: sg_access_key
      MINIO_SECRET_KEY: sg_secret_key
      MINIO_ETCD_ENDPOINTS: http://etcd:2379
      MINIO_CACHE: 'on'
      MINIO_CACHE_DRIVES: /storage
      MINIO_CACHE_EXPIRY: 365
      MINIO_CACHE_EXCLUDE: '*.pdf'
      MINIO_CACHE_QUOTA: 100
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint: /bin/wait-for-it.sh -t 0 etcd:2379 -- minio gateway s3
    depends_on:
      - etcd
networks:
  internal-network:
    driver: bridge
volumes:
  storage:
